spring.application.name=demo-backend
# Enable the H2 Console (Optional, for web browser access)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configure the file-based database path
spring.datasource.url=jdbc:h2:file:./data/mydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# Retain the database structure across restarts
spring.jpa.hibernate.ddl-auto=update